use strict;
package main;
print("<html>\n");
print("	<head>\n");
print("		<meta http-equiv=\"content-type\" content=\"text/html;charset=iso-8859-1\">\n");
print("		<title>PerfStat: Performance And Status Monitor</title>\n");
print("		<link type=\"text/css\" rel=\"stylesheet\" href=\"../appRez/styleSheets/login.css\">\n");
print("		<link type=\"text/css\" rel=\"stylesheet\" href=\"../appRez/styleSheets/forms.css\">\n");
print("	</head>\n");
print("	<body>\n");
print("		<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n");
print("			<tr>\n");
print("				<td><img src=\"../appRez/images/common/spacer.gif\" width=\"40\" height=\"60\" border=\"0\"></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td valign=\"top\" align=\"center\">\n");
print("					<form name=\"loginForm\" action=\"index.pl\" method=\"post\">\n");
print("					<input type=\"hidden\" name=\"action\" value=\"doLogin\">\n");
print("					<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"table1\">\n");
print("						<tr>\n");
print("							<td class=\"header\" valign=\"top\" align=\"left\">\n");
print("									<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n");
print("										<tr>\n");
print("											<td width=\"171\"><img src=\"../appRez/images/header/logo.gif\" width=\"171\" height=\"51\" border=\"0\"></td>\n");
print("											<td valign=\"top\" align=\"right\">\n");
print("												<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n");
print("													<tr>\n");
print("														<td valign=\"top\" align=\"right\"><span class=\"blurb\">PERFORMANCE AND STATUS MONITOR</span></td>\n");
print("													</tr>\n");
print("													<tr>\n");
print("														<td><img src=\"../appRez/images/common/spacer.gif\" width=\"100\" height=\"8\" border=\"0\"></td>\n");
print("													</tr>\n");
print("													<tr>\n");
print("														<td class=\"stripe\"><img src=\"../appRez/images/common/spacer.gif\" width=\"300\" height=\"2\" border=\"0\"></td>\n");
print("													</tr>\n");
print("													<tr>\n");
print("														<td></td>\n");
print("													</tr>\n");
print("												</table>\n");
print("											</td>\n");
print("										</tr>\n");
print("									</table>\n");
print("								</td>\n");
print("						</tr>\n");
print("							<tr>\n");
print("								<td valign=\"top\" align=\"center\"><img src=\"../appRez/images/common/spacer.gif\" width=\"40\" height=\"20\" border=\"0\"></td>\n");
print("							</tr>\n");
print("							<tr>\n");
print("							<td valign=\"top\" align=\"center\">\n");
print("									<table border=\"0\" cellpadding=\"0\" cellspacing=\"7\">\n");
print("										<tr>\n");
my $formula0=$userErrorMessage;print("											<td nowrap valign=\"middle\" align=\"left\" colspan=\"2\"><span class=\"userErrorMessage\">$formula0</span></td>\n");
print("										</tr>\n");
print("										<tr>\n");
print("										<td nowrap valign=\"middle\" align=\"right\">User Name</td>\n");
my $formula1=$userName;print("										<td><input name=\"userName\" value=\"$formula1\" size=\"24\" maxlength=\"80\" ></td>\n");
print("									</tr>\n");
print("									<tr>\n");
print("										<td valign=\"middle\" align=\"right\">Password</td>\n");
my $formula2=$password;print("										<td><input type=\"password\" name=\"password\" value=\"$formula2\"size=\"24\"  maxlength=\"20\"></td>\n");
print("									</tr>\n");
print("								</table>\n");
print("							</td>\n");
print("						</tr>\n");
print("							<tr>\n");
print("								<td valign=\"middle\" align=\"center\"><img src=\"../appRez/images/common/spacer.gif\" width=\"40\" height=\"20\" border=\"0\"></td>\n");
print("							</tr>\n");
print("							<tr>\n");
print("								<td valign=\"middle\" class=\"footer\" align=\"center\"><input class=\"liteButton\" type=\"submit\" value=\"   LOG IN   \"></td>\n");
print("							</tr>\n");
print("						</table>\n");
print("					</form>\n");
print("				</td>\n");
print("			</tr>\n");
print("		</table>\n");
print("	</body>\n");
print("</html>\n");
