use strict;
package main;
print("<html>\n");
print("	<head>\n");
print("		<meta http-equiv=\"content-type\" content=\"text/html;charset=iso-8859-1\">\n");
print("		<title>PerfStat Tool: Status And Performance Monitoring</title>\n");
print("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../../../appRez/styleSheets/contentFrame.css\" media=\"screen\">\n");
print("	</head>\n");

print("	<body>\n");
print("		<div class=\"navHeader\">\n");
my $formula0=$sessionObj->param("groupViewStatus") ne "shared" ?  "My HostGroups" : "Shared HostGroups";my $formula1=$sessionObj->param("hostName");print("			<div class=\"navHeader\">Asset Monitor :: <a href=\"../level1/index.pl?doToggle=1\">$formula0</a> :: $formula1</div>\n");
print("		</div>\n");
print("		<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n");
print("			<tr valign=\"top\">\n");
print("				<td>\n");
 my $ip = $hostObject->getOS();
 my $os = $hostObject->getOS();
 my $osVer = $hostObject->getOsVer();
 my $kernelDescriptor;
 if ($os ne "WindowsNT") {
$kernelDescriptor ="Kernel Version:";
 } else {
$kernelDescriptor ="Service Pack:";
}
 my $kernelVer = $hostObject->getKernelVer();
 my $cpuNum = $hostObject->getCpuNum();
 my $cpuModel = $hostObject->getCpuModel();
 my $cpuSpeed = $hostObject->getCpuSpeed();
 my $memTotal = $hostObject->getMemTotal();
 my $patchArray = $hostObject->getPatchesArray();
print("					<table cellpadding=\"2\" cellspacing=\"1\" border=\"0\" class=\"table1\">\n");
print("						<tr>\n");
my $formula2=$sessionObj->param("hostName");print("							<td class=\"tdTop\" nowrap colspan=\"2\" valign=\"middle\" align=\"left\">$formula2</td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<th nowrap valign=\"middle\" align=\"left\" width=\"5%\">Property</th>\n");
print("							<th nowrap valign=\"middle\" align=\"left\">Value</th>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td  class=\"liteGray\" nowrap valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">CPU Model:</span></td>\n");
my $formula3=$cpuModel;print("							<td  class=\"liteGray\" valign=\"top\" align=\"left\"><span class=\"table1Text2\">$formula3</span></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td  class=\"liteGray\" nowrap valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">CPU Speed:</span></td>\n");
my $formula4=$cpuSpeed;print("							<td class=\"liteGray\" valign=\"top\" align=\"left\"><span class=\"table1Text2\">$formula4 MHz</span></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td  class=\"liteGray\" nowrap valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">Number of CPUs:</span></td>\n");
my $formula5=$cpuNum;print("							<td class=\"liteGray\" valign=\"top\" align=\"left\"><span class=\"table1Text2\">$formula5</span></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td  class=\"liteGray\" nowrap valign=\"top\" align=\"right\" width=\"5%\"></td>\n");
print("							<td class=\"liteGray\" valign=\"top\" align=\"left\"></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td  class=\"liteGray\" nowrap valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">Total Memory:</span></td>\n");
my $formula6=$memTotal;print("							<td  class=\"liteGray\" valign=\"top\" align=\"left\"><span class=\"table1Text2\">$formula6 MB</span></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td  class=\"liteGray\" nowrap valign=\"top\" align=\"right\" width=\"5%\"></td>\n");
print("							<td class=\"liteGray\" valign=\"top\" align=\"left\"></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td nowrap  class=\"liteGray\" valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">OS:</span></td>\n");
my $formula7=$os;print("							<td  class=\"liteGray\" valign=\"top\" align=\"left\"><span class=\"table1Text2\">$formula7</span></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td nowrap  class=\"liteGray\" valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">OS Version:</span></td>\n");
my $formula8=$osVer;print("							<td  class=\"liteGray\" valign=\"top\" align=\"left\"><span class=\"table1Text2\">$formula8</span></td>\n");
print("						</tr>\n");
print("						<tr>\n");
my $formula9=$kernelDescriptor;print("							<td nowrap  class=\"liteGray\" valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">$formula9</span></td>\n");
my $formula10=$kernelVer;print("							<td  class=\"liteGray\" valign=\"top\" align=\"left\"><span class=\"table1Text2\">$formula10</span></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td  class=\"liteGray\" nowrap valign=\"top\" align=\"right\" width=\"5%\"></td>\n");
print("							<td class=\"liteGray\" valign=\"top\" align=\"left\"></td>\n");
print("						</tr>\n");
print("						<tr>\n");
print("							<td nowrap  class=\"liteGray\" valign=\"top\" align=\"right\" width=\"5%\"><span class=\"table1Text2\">Patch List</span></td>\n");
print("							<td  class=\"liteGray\" valign=\"top\" align=\"left\">\n");
print("								<span class=\"table1Text2\">\n");
foreach my $patchName (sort(@$patchArray)) {
my $formula11=$patchName;print("								 	$formula11,&nbsp;\n");
}
print("								</span>\n");
print("							</td>\n");
print("						</tr>\n");
print("					</table>\n");
print("				</td>\n");
print("			</tr>\n");
print("		</table>\n");
print("	</body>\n");
print("</html>\n");
