use strict;
package main;
print("<html>\n");
print("	<head>\n");
print("		<meta http-equiv=\"content-type\" content=\"text/html;charset=iso-8859-1\">\n");
print("		<title>PerfStat Tool: Perfomance Monitoring & Status Notification</title>\n");
print("		<link rel=\"stylesheet\" type=\"text/css\" href=\"../../appRez/styleSheets/contentFrame.css\" media=\"screen\">\n");
print("	</head>\n");

print("	<body onLoad=\"parent.navigation.setLinkChosen('serverStatus');\">\n");
print("		<div class=\"navHeader\">Status Monitor :: PerfStat Server</div>\n");
print("		<table width=\"100%\" cellpadding=\"2\" cellspacing=\"1\" border=\"0\" class=\"table1\">\n");
print("			<tr>\n");
print("				<td class=\"tdTop\" nowrap=\"nowrap\" colspan=\"2\" valign=\"top\" align=\"left\">Server Status</td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" width=\"10%\"><span class=\"table1Text2\">Status</span></td>\n");
my $formula0=$serverStatus;print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">The server is $formula0</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" width=\"10%\"><span class=\"table1Text2\">Uptime</span></td>\n");
my $formula1=$uptime;print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula1</span></td>\n");
print("			</tr>\n");
print("		</table>\n");
print("		<table width=\"100%\" cellpadding=\"2\" cellspacing=\"1\" border=\"0\" class=\"table1\">\n");
print("			<tr>\n");
print("				<td class=\"tdTop\" nowrap=\"nowrap\" colspan=\"2\" valign=\"top\" align=\"left\">Server Settings</td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" width=\"10%\"><span class=\"table1Text2\">IP </span></td>\n");
my $formula2=$ENV{'PERFSERVER'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula2</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" width=\"10%\"><span class=\"table1Text2\">Port</span></td>\n");
my $formula3=$ENV{'SERVERPORT'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula3</span></td>\n");
print("			</tr>\n");
print("		</table>\n");
print("		<table width=\"100%\" cellpadding=\"2\" cellspacing=\"1\" border=\"0\" class=\"table1\">\n");
print("			<tr>\n");
print("				<td class=\"tdTop\" nowrap=\"nowrap\" colspan=\"2\" valign=\"top\" align=\"left\">Email Settings</td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Email </span></td>\n");
my $formula4=$ENV{'EMAIL'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula4</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Email All</span></td>\n");
my $formula5=$ENV{'EMAIL_ALL'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula5</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Email Crit</span></td>\n");
my $formula6=$ENV{'EMAIL_CRIT'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula6</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Email Warn</span></td>\n");
my $formula7=$ENV{'EMAIL_WARN'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula7</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">SMTP Server</span></td>\n");
my $formula8=$ENV{'SMTP_SERVER'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula8</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Email To</span></td>\n");
my $formula9=$ENV{'EMAIL_TO'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula9</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Email From</span></td>\n");
my $formula10=$ENV{'EMAIL_FROM'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula10</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Email Subject</span></td>\n");
my $formula11=$ENV{'EMAIL_SUBJECT'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula11</span></td>\n");
print("			</tr>\n");
print("		</table>\n");
print("		<table width=\"100%\" cellpadding=\"2\" cellspacing=\"1\" border=\"0\" class=\"table1\">\n");
print("			<tr>\n");
print("				<td class=\"tdTop\" nowrap=\"nowrap\" colspan=\"2\" valign=\"top\" align=\"left\">Event Log Settings</td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Log Events</span></td>\n");
my $formula12=$ENV{'EVENTLOG'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula12</span></td>\n");
print("			</tr>\n");
print("			<tr>\n");
print("				<td class=\"liteGray\" align=\"right\" valign=\"middle\" nowrap width=\"10%\"><span class=\"table1Text2\">Log Size</span></td>\n");
my $formula13=$ENV{'LOGSIZE'};print("				<td class=\"liteGray\" nowrap=\"nowrap\"><span class=\"table1Text2\">$formula13</span></td>\n");
print("			</tr>\n");
print("		</table>\n");
print("	</body>\n");
print("</html>\n");
